[theme]
primaryColor = "#1b285c"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#ffffff"
textColor = "#000000"
font = "sans serif"

[server]
maxUploadSize = 50
maxMessageSize = 50
enableCORS = false
enableXsrfProtection = true
